import 'package:synerise_flutter_sdk/enums/vouchers/voucher_code_status.dart';
import '../../utils/synerise_utils.dart';

class PromotionVoucherData {
  String code;
  VoucherCodeStatus status;
  bool autoGenerated;
  DateTime assignedAt;
  DateTime? lastingAt;
  DateTime? redeemedAt;
  
  PromotionVoucherData._({
    required this.code,
    required this.status,
    required this.autoGenerated,
    required this.assignedAt,
    this.lastingAt,
    this.redeemedAt,
  });

  /// `PromotionVoucherData.fromMap(Map map)` is a factory constructor that creates a new instance of the
  /// `PromotionVoucherData` class from a `Map` object. It takes a `Map` object as an argument and uses the values
  /// from the map to initialize the properties of the `PromotionVoucherData` object. It returns a new instance of
  /// the `PromotionVoucherData` class with the properties set to the values from the `Map`.
  PromotionVoucherData.fromMap(Map map)
      : this._(
          code: map['code'],
          status:
              VoucherCodeStatus.getVoucherCodeStatusFromString(map['status']),
          autoGenerated: map['autoGenerated'],
          assignedAt: SyneriseUtils.formatIntToDateTime(map['assignedAt']),
          lastingAt: map['lastingAt'] != null
              ? SyneriseUtils.formatIntToDateTime(map['lastingAt'])
              : null,
          redeemedAt: map['redeemedAt'] != null
              ? SyneriseUtils.formatIntToDateTime(map['redeemedAt'])
              : null,
        );
}